// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omwysabwktujojezgplj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9td3lzYWJ3a3R1am9qZXpncGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDg0NTYsImV4cCI6MjA2OTk4NDQ1Nn0.0N7zxCz9BOwKlA0kboAu7GGpnuwTCz_AreJ7H7Wyg38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});